services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    command: named -c /data/bind/named.conf -g
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./bind9:/data/bind
    networks:
      - traefik

networks:
  traefik:
    external: true
