services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    command: -g -c /etc/bind/named.conf
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/zones:/var/lib/bind
      - ./bind9/cache:/var/cache/bind
    networks:
      - traefik

networks:
  traefik:
    external: true