services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    command: named -c /etc/bind/named.conf -g
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/zones:/etc/bind/zones
    networks:
      - traefik

networks:
  traefik:
    external: true