services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    command: -g -c /etc/bind/named.conf
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/zones:/var/lib/bind
      - ./bind9/cache:/var/cache/bind
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=your-email@example.com
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_API_EMAIL=your-cloudflare-email
      - CF_DNS_API_TOKEN=your-cloudflare-api-token
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/letsencrypt/acme.json
    networks:
      - internal

  db:
    image: postgres:15
    container_name: authentik-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: authentikpass
      POSTGRES_DB: authentik
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  authentik:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik
    depends_on:
      - db
    environment:
      AUTHENTIK_SECRET_KEY: "supersecretkey"
      DATABASE_URL: "postgresql://authentik:authentikpass@db:5432/authentik"
      AUTHENTIK_EMAIL__HOST: "smtp.example.com"
      AUTHENTIK_EMAIL__PORT: "587"
      AUTHENTIK_EMAIL__USERNAME: "mail@example.com"
      AUTHENTIK_EMAIL__PASSWORD: "mailpassword"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=cloudflare"
    networks:
      - internal



  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    command: worker
    depends_on:
      - db
    environment:
      AUTHENTIK_SECRET_KEY: "supersecretkey"
      DATABASE_URL: "postgresql://authentik:authentikpass@db:5432/authentik"
    networks:
      - internal




networks:
  internal:
    driver: bridge

volumes:
  db_data:
