## STATIC CONFIGURATION
log:
  level: INFO

api:
  dashboard: true
  # Deaktiviere den unsicheren Modus, da wir das Dashboard über einen Router konfigurieren
  insecure: false

entryPoints:
  web:
    address: ":80"
    # HTTP zu HTTPS Umleitung direkt in der statischen Konfiguration
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`{{ normalize .Name }}.${DOMAIN}`)"
  file:
    filename: "/dynamic-config.yml"

certificatesResolvers:
  cloudflare:
    acme:
      email: "${EMAIL}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

serversTransport:
  insecureSkipVerify: true
